### ISSUE TITLE
Streaming issue

### ISSUE THREAD

**Issue by houah** [gmickel/memorybot#6]
I have noticed that when using chain.call() the full answer is sent instead of being streamed.
So looking at the console, the output is correctly streamed by CallbackManager, but in the end if the output had to be written somewhere else, only the full answer would be delivered.
Am I right or did I miss something ?
Is it possible to have a streaming with chain.call ?

**Comment by gmickel** [comment]
You are correct, this is how LangChain implements streaming. If you are outputting to something other than the console/stdout you would need to adapt the `handleLLMNewToken` method in the CallbackManager.

**Comment by houah** [comment]
Hi 

Thanks for your reply :-)

I noticed that you added the ability to have several different vectorstores ! wonderful as we could set on per different user :-)

Just a question : would HNSWLib allow to delete vectors based on metadata ?

I mean it’s cool to upload documents, but if they need to be deleted or updated, how could I delete or update the corresponding vectors in HNSWLib ?

That would be an issue if the bot answers with old data

any suggestion on this ?

Maybe an implementation of Pinecone would do better ?

What are your ideas on this ?

Best regards
Jean

**Comment by gmickel** [comment]
Hello there!

I designed this with the intention for it to function as a standalone application that is not only easy to set up but also free from dependencies on other services, with the exception of OpenAI.

Should your project requirements become more complex, where there's a necessity to synchronise your vector stores, delete, or replace outdated embeddings, it may be advisable to consider transitioning away from HNSWLib. Pinecone is definitely an option but I've also had great success with postgres (pgvector, redis and others.

**Comment by houah** [comment]
Hi and thanks for your feedback In fact I’ll have a few hundred users who would upload say 10 to 100 docs each. I have set up users folder so that’s ok. But they may have to occasionally delete a doc or upgrade one. I was thinking at writing a method to retrieve the doc with its metadata name already stored, and either suppress it or upgrade it. My question was whether the HNSWlib index would be automatic updated with this or not ?Could you share your thoughts and experience about this ?I like your approach of trying to keep things simple but lack experience about all thisThanks a lot for your time Bien cordialement, Jean ***@***.*** https://activ-ha.com Le 27 mai 2023 à 15:20, Gordon Mickel ***@***.***> a écrit :﻿
Hello there!
I designed this with the intention for it to function as a standalone application that is not only easy to set up but also free from dependencies on other services, with the exception of OpenAI.
Should your project requirements become more complex, where there's a necessity to synchronise your vector stores, delete, or replace outdated embeddings, it may be advisable to consider transitioning away from HNSWLib. Pinecone is definitely an option but I've also had great success with postgres (pgvector, redis and others.

**Comment by gmickel** [comment]
If you want to keep using HNSWLib-node then you should be able to, it's only a thin wrapper around the actual hnswlib library and does support at least some but maybe all of the features you need. This comment here might get you started: https://github.com/yoshoku/hnswlib-node/issues/36#issuecomment-1427048473

**Comment by houah** [comment]
So you mean that within your code getContextVectorStore.markDelete(docID) where docID is the id of the document in doctor.json would be enough to mark it as deleted ?

In this case it could be something like adding the name of the added file in the metadata, then using something like :

`function getDocIDsByMetadata(documents: [string, { pageContent: string, metadata: Record<string, any> }][], metadataKey: string, metadataValue: any): string[] {
  const docIDs: string[] = [];

  for (const [docID, { metadata }] of documents) {
    if (metadata && metadata[metadataKey] === metadataValue) {
      docIDs.push(docID);
    }
  }

  return docIDs;
}


async function deleteDocument(userEnv: UserEnvironment, metadataKey: string, metadataValue: any) {
  const docStore = await getContextVectorStore(userEnv);
  const documents = Object.entries(docStore);

  // Récupérer les IDs des documents correspondant aux métadonnées
  const docIDs = getDocIDsByMetadata(documents, metadataKey, metadataValue);

  // Supprimer les documents correspondants de l'index avec markDelete de hnswlib-node et delete pour le docstore : https://github.com/yoshoku/hnswlib-node/issues/36#issuecomment-1427048473
  for (const docID of docIDs) {
  	docStore.markDelete(docID);
    delete docStore[docID];
  }

  await docStore.save(dbDirectory(userEnv));
}
`
