### ISSUE TITLE
How can I add recording and transcribe my voice with Whisper AI and TTS with the answering from chatbot.

### ISSUE THREAD

**Issue by jonnytri53** [gmickel/memorybot#7]
Hi Dev and community,
First of all, I'm sorry to post it here, it's not really an issue with the code. But I wanna ask how I can record and transcribe my voice with Whisper AI and TTS with the answering from a chatbot later. I'm new to code, and I think that much easier to do it with Python code (because a lot of guidance with Python), but I have no idea how to do the same thing with Typescripts. I just need to give some ideas. Which files should I modify, or create, and do any recommendations for the library on Github to build it? Thank you so much. I'd appreciate it.

**Comment by gmickel** [comment]
Hi @jonnytri53 

Sorry for the late reply.

This is quite out-of-scope for this library but I can point you to [this article](https://medium.com/codingthesmartway-com-blog/speech-to-text-use-node-js-and-openais-whisper-api-to-record-transcribe-in-one-step-c9a1fd441765) which might be useful.
