### ISSUE TITLE
Azure OpenAI

### ISSUE THREAD

**Issue by stevenbaert** [gmickel/memorybot#8]
Can you make the script with Azure OpenAI ChatGPT?

**Comment by ishaan-jaff** [comment]
Hi @stevenbaert @gmickel  I believe we can help with this issue. I’m the maintainer of LiteLLM https://github.com/BerriAI/litellm

**TLDR:**
**We allow you to use any LLM as a drop in replacement for `gpt-3.5-turbo`. 
If you don't have access to the LLM you can use the LiteLLM proxy to make requests to the LLM**

You can use LiteLLM in the following ways:

## With your own API KEY:
This calls the provider API directly

```python
from litellm import completion
import os
## set ENV variables 
os.environ["OPENAI_API_KEY"] = "your-key" # 
os.environ["COHERE_API_KEY"] = "your-key" # 

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages=messages)
```

## Using the LiteLLM Proxy with a LiteLLM Key 
this is great if you don’t have access to claude but want to use the open source LiteLLM proxy to access claude


```python
from litellm import completion
import os

## set ENV variables 
os.environ["OPENAI_API_KEY"] = "sk-litellm-5b46387675a944d2" # [OPTIONAL] replace with your openai key
os.environ["COHERE_API_KEY"] = "sk-litellm-5b46387675a944d2" # [OPTIONAL] replace with your cohere key

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages=messages)
```

**Comment by gmickel** [comment]
Hi @stevenbaert 

LangChain's OpenAI classes support Azure OpenAI [out of the box](https://js.langchain.com/docs/modules/model_io/models/chat/integrations/azure). You should be able to make the script work with Azure by changing the class instantiation in src/index.ts.
