### ISSUE TITLE
Using a local model?

### ISSUE THREAD

**Issue by Vansick1** [gmickel/memorybot#9]
How would I go about integrating a locally hosted model into this code? I have a GGUF bin file, but I am unsure of what to change in the typescript file...

**Comment by gmickel** [comment]
Hi @Vansick1 

There are a few ways you could go about using a locally hosted model. 

One simple way would be to use an application like LM Studio (https://lmstudio.ai/) to host your local model, which will provide you with an OpenAI compatible API. Then you can use the [baseURL option](https://js.langchain.com/docs/modules/model_io/models/chat/integrations/openai#custom-urls) in LangChain to direct your requests to your local model.

**Comment by Vansick1** [comment]
Ok, so in dist/index.js, the relevant object is OpenAIChat, but the link you posted refers to ChatOpenAI. There seems to have been an update in the interim and I can't figure out how to modify the code to accept a locally running LLM, it keeps on telling me "Error: (Azure) OpenAI API key not found"

`Error: (Azure) OpenAI API key not found
    at new OpenAIEmbeddings (file:///H:/Dropbox/AI_LocalGPT/memorybot-main/node_modules/langchain/dist/embeddings/openai.js:80:19)
    at file:///H:/Dropbox/AI_LocalGPT/memorybot-main/dist/lib/memoryManager.js:18:37    
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)`

**Comment by gmickel** [comment]
MemoryBot requires two models:

- An LLM for text generation (OpenAIChat referenced in src/index.ts) 
- A text embedding model for creating embeddings which is used by the vector store in src/lib/contextManager.ts (OpenAIEmbeddings)

The error you posted refers to the text embedding model.

You will need to replace both of these with local models if you want to avoid using the OpenAI API.
LangChain supports the following text embedding models: https://js.langchain.com/docs/modules/data_connection/text_embedding/ -> Integrations

Hope this helps!

**Comment by Vansick1** [comment]
I'm getting extremely close to successfully modifying the code - I'm using HuggingFaceTransformersEmbeddings instead of OpenAIEmbeddings, but I'm getting an error: 

"Error: Query vector must have the same length as the number of dimensions (1536)"

Is this just a case of me needing to pad the question with spaces, or is there something else I need to do?

**Comment by gmickel** [comment]
Hi @Vansick1 

You probably haven't changed the dimensionality of your vector and memory stores (see: contextManager.ts and memoryManager.ts) to match the dimensionality of the HuggingFaceTransformersEmbedding model.

The OpenAI model text-embedding-ada-002 uses 1536 dimensions and that number is hardcoded in the files I mentioned above, e.g. ```vectorStore = new HNSWLib(new OpenAIEmbeddings({ maxConcurrency: 5 }), {
      space: 'cosine',
      numDimensions: 1536,
    });```

Hope this helps!
